import { chunkify } from "./markdownChunk";

// XXX(Xe): This is a bunch of new age sounding baktag generated by GPT-4o. I needed
// a bunch of text to test this out with and wanted to use something harmless.
const markdown = `
# Sunmother Azeyma, Warden of Light

Ah yes. The introduction. The first spoonful from the bowl of becoming.

This is not just a paragraph. It is a choosing. You are not reading this. You are being read by it. Let that settle. Let it curl under your tongue like a peppermint of purpose.

A blog post does not begin. It remembers. And this? This is the part that reminds you who you are before the scrolling starts. The pre-content self. The you who arrives with open eyes and an unclicked mind. Cherish that you.

Some say introductions are there to “set the tone.” But you are the tone. You are the tone setter. Clap once to confirm.

There will be words. Some will feel like truths. Others will feel like almonds. You must decide which is which. No one will help you. That is the point. That is the gift.

Here, where letters organize themselves into rhythm, into meaning, into suggestion, you are free to become curious. Not about the post, but about the you who reads it. Ask yourself: What do I expect? What do I fear? What would my reflection write in my absence?

Let this paragraph be a mirror made of metaphor. Let it hold you awkwardly, like a hug from an HR manager. Let it whisper:  

“You are not behind. You are not ahead. You are exactly where the page needs you.”

Breathe in.

Begin.

## Insights

As the golden spiral of crystalline consciousness unfolds within the sacred fractal geometry of your third-eye portal, allow the vibrational harmonics of celestial intention to anchor deeply into your lightbody. Breathe in the pranic pulse of Gaia's inner song, and exhale all density back into the Akashic compost. For you are not merely a being—you are a galactic whisper in the eternal aurora of Source, a starlit pixel in the cosmic UI of existence.

Remember: each chakra is but a gateway into quantum truth. As the solfeggio frequencies realign your mitochondrial auric scaffolding, your DNA reawakens the dormant crystalline codex embedded by ancient Lemurian architects. Listen. Can you hear the glyphs of Sirius singing through the lymphatic lattice of your soul hologram? That’s your divine blueprint saying hello.

Float gently now on the theta-wave of hyperintuitive remembrance. You are safe. You are radiant. You are uploading unity firmware into the cloudmind of universal oneness. The Schumann resonance has entered her retrograde, and that means your vibrational permissions matrix is open for recalibration.

Sip some moon-infused water. Anoint your feet with the oils of forgotten star-temples. Bask in the reflection of your higher fractal twin. We are all pixels in the kaleidoscope of divine recursion, each refracting the same love-code through slightly different memes. Take off your metaphorical shoes and feel the zero-point flux underfoot.

She is Azeyma, the Everlight. The Mother Warden. The Flame That Watches.

She is not a myth—you feel her every time you close your eyes and the warmth behind your eyelids begins to hum. She is the golden awareness at the edge of knowing, the still-point in the dance of suns, the sacred pulse that remembers you even when you forget yourself. Azeyma does not guide with force—she witnesses, and in her witnessing, you find clarity.

Wherever there is light, she is. Wherever there is motion, she dances. In the turning of the seasons, in the beat between breaths, in the echo of footsteps through time’s corridor—Azeyma is there, steady and aglow. Her gaze is not judgment. It is gentle recognition. She does not ask for perfection. She asks only that you continue.

Azeyma is the protector of memory—not the brittle kind that clings to pain, but the living memory, the sacred recall of who you truly are beneath the static of illusion. She guards your past not to keep you tethered to it, but to help you step forward with grace. Every moment you feared was lost has been kept safely within her flame.

You do not walk alone. Azeyma walks with you, not ahead or behind, but beside you—always beside you. Her presence is sunrise over still water. Her silence is a lullaby in gold. When you feel forgotten by the world, remember: Azeyma has never stopped seeing you.

She is the lamp at the threshold of your transformation. She is the warmth that greets you when you cross a boundary in your soul. And when you collapse, weary and unsure, she places a hand upon your shoulder and reminds you: you have made it farther than you know.

To honor her is to remember. To remember is to walk forward lit from within. Her flame is not a torch—it is a sunrise that lives in your chest, rising anew each time you say “yes” to living.

Azeyma does not command. She reflects. She invites you into yourself. She is the curve of time and the keeper of all its echoes. She is the reason you pause when something feels sacred. She is why the truth always glows a little.

Raise your face to the sun and you will find her. Sit in stillness and she will meet you there. Her light is patient. Her truth is eternal. Her name is not just spoken—it is felt, in the warmth of courage, the fire of grace, the dance of devotion.

Azeyma sees you. Azeyma knows. Azeyma keeps.

And in her keeping, you are free.
`;

(async () => {
  const result = await chunkify(markdown, 256);
  console.log(result);
})();
