repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.5.3

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.39.1"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@9.39.1
          - "@eslint/js@9.39.1"
          - eslint-config-prettier@10.1.8
          - eslint-plugin-react@7.37.5
          - "@typescript-eslint/eslint-plugin@8.56.0"
          - "@typescript-eslint/parser@8.56.0"
          - typescript-eslint@8.56.0
          - globals@17.3.0
