/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
// };

/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  quickstarts: [
    {
      type: "doc",
      id: "index",
      label: "Home",
    },
    {
      type: "category",
      label: "Get Started",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "Use the Tigris CLI",
          id: "cli/index",
        },
        {
          type: "doc",
          label: "Use the Tigris SDK",
          id: "sdks/tigris/index",
        },
        {
          type: "doc",
          label: "Use Your Existing S3 Code",
          id: "sdks/s3/index",
        },
        {
          type: "category",
          label: "Use AI",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "MCP Quickstart",
              id: "quickstarts/mcp",
            },
            {
              type: "doc",
              label: "Agent Skills",
              id: "skills",
            },
            {
              type: "doc",
              label: "Agent Plugins",
              id: "ai/agent-plugins",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Overview",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "overview/index",
      },
      items: [
        {
          type: "doc",
          label: "What is Tigris?",
          id: "overview/index",
        },
        {
          type: "doc",
          label: "Features",
          id: "overview/features",
        },
        {
          type: "category",
          label: "Concepts",
          collapsible: true,
          collapsed: true,
          items: [
            "concepts/architecture",
            "concepts/authnz",
            "concepts/consistency",
            "concepts/regions",
            "api/s3/index",
          ],
        },
        {
          type: "category",
          label: "Benchmarks",
          link: {
            type: "doc",
            id: "overview/benchmarks/index",
          },
          items: [
            {
              type: "category",
              label: "Small Object Benchmark",
              items: [
                {
                  type: "doc",
                  label: "Performance Metrics",
                  id: "overview/benchmarks/metrics",
                },
                {
                  type: "doc",
                  label: "Comparison: AWS S3",
                  id: "overview/benchmarks/aws-s3",
                },
                {
                  type: "doc",
                  label: "Comparison: Cloudflare R2",
                  id: "overview/benchmarks/cloudflare-r2",
                },
                {
                  type: "doc",
                  label: "Benchmark Summary",
                  id: "overview/benchmarks/summary",
                },
              ],
            },
            {
              type: "category",
              label: "Model Training Benchmark",
              items: [
                {
                  type: "doc",
                  label: "Model Training on Tigris",
                  id: "overview/benchmarks/model-training",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Compare to Tigris",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "Compare to AWS S3",
              id: "overview/compare/aws-s3",
            },
            {
              type: "doc",
              label: "Compare to Google Cloud Storage",
              id: "overview/compare/google-cloud-storage",
            },
            {
              type: "doc",
              label: "Compare to Cloudflare R2",
              id: "overview/compare/cloudflare-r2",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Use Cases",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Agent Storage",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "Agent Coordination",
              id: "use-cases/agent-coordination",
            },
            {
              type: "doc",
              label: "Agent Managed Storage",
              id: "use-cases/agent-managed-storage",
            },
            {
              type: "doc",
              label: "Agent Sandboxes",
              id: "use-cases/agent-sandboxes",
            },
          ],
        },
        {
          type: "category",
          label: "Training & Inference",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "Store and Serve Models",
              id: "model-serving-use-cases",
            },
            {
              type: "doc",
              label: "Stream Training Datasets",
              id: "use-cases/stream-training-datasets",
            },
            {
              type: "doc",
              label: "Preload Data for HPC",
              id: "use-cases/preload-data-hpc",
            },
            {
              type: "doc",
              label: "Trigger Pipelines",
              id: "use-cases/trigger-pipelines",
            },
            {
              type: "doc",
              label: "Checkpoint, Restore, & Fork",
              id: "use-cases/checkpoint-restore-fork",
            },
          ],
        },
        {
          type: "category",
          label: "Platforms",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "Multi-Tenant Storage",
              id: "use-cases/multitenant-storage",
            },
            {
              type: "doc",
              label: "Backups & Archives",
              id: "use-cases/backup-archive",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Languages & Frameworks",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "Python",
              id: "quickstarts/python",
            },
            {
              type: "doc",
              label: "PyTorch",
              id: "quickstarts/pytorch",
            },
            {
              type: "doc",
              label: "Go",
              id: "quickstarts/go",
            },
            {
              type: "doc",
              label: "Node.js",
              id: "quickstarts/node",
            },
            {
              type: "doc",
              label: "Kubernetes",
              id: "quickstarts/kubernetes",
            },
            {
              type: "doc",
              label: "Terraform",
              id: "terraform/index",
            },
            {
              type: "doc",
              label: "rclone",
              id: "quickstarts/rclone",
            },
          ],
        },
        {
          type: "category",
          label: "Migrate to Tigris",
          collapsed: true,
          link: {
            type: "doc",
            id: "migration/index",
          },
          items: [
            "migration/aws-s3",
            "migration/gcs",
            "migration/cloudflare-r2",
            "migration/minio",
            "migration/s3-compatible",
          ],
        },
        {
          type: "category",
          label: "Integrations",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "category",
              label: "AI & ML",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "category",
                  label: "SkyPilot",
                  items: [
                    {
                      type: "doc",
                      label: "Getting Started",
                      id: "quickstarts/skypilot",
                    },
                    {
                      type: "doc",
                      label: "Model Storage",
                      id: "model-storage/skypilot",
                    },
                    {
                      type: "doc",
                      label: "Training With Big Data",
                      id: "training/big-data-skypilot/index",
                    },
                  ],
                },
                {
                  type: "category",
                  label: "LanceDB",
                  items: [
                    {
                      type: "doc",
                      label: "Getting Started",
                      id: "libraries/lancedb/index",
                    },
                    {
                      type: "doc",
                      label: "Choosing a Lance Dataset Type",
                      id: "libraries/lancedb/choosing-dataset-type",
                    },
                    {
                      type: "doc",
                      label: "Vector Database Tutorial",
                      id: "libraries/lancedb/vector-database",
                    },
                    {
                      type: "doc",
                      label: "Example: Document Search",
                      id: "libraries/lancedb/docs-search",
                    },
                  ],
                },
                {
                  type: "doc",
                  label: "Pixeltable",
                  id: "quickstarts/pixeltable",
                },
                {
                  type: "doc",
                  label: "CrewAI",
                  id: "agents/agent-crewai",
                },
                {
                  type: "doc",
                  label: "Cognee",
                  id: "agents/agent-cognee",
                },
                {
                  type: "doc",
                  label: "Weka",
                  id: "guides/weka",
                },
              ],
            },
            {
              type: "category",
              label: "Data & Analytics",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  label: "DuckDB",
                  id: "quickstarts/duckdb",
                },
                {
                  type: "doc",
                  label: "Databricks",
                  id: "libraries/databricks/index",
                },
              ],
            },
            {
              type: "category",
              label: "Streaming & Messaging",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  label: "Bufstream",
                  id: "quickstarts/bufstream",
                },
                {
                  type: "doc",
                  label: "AutoMQ",
                  id: "quickstarts/automq",
                },
                {
                  type: "doc",
                  label: "Warpstream",
                  id: "guides/warpstream",
                },
              ],
            },
            {
              type: "category",
              label: "Infrastructure",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  label: "Fly.io",
                  id: "sdks/fly/index",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "html",
      value: '<hr class="sidebar-divider" />',
      defaultStyle: false,
    },
    {
      type: "category",
      label: "Product",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Account Management",
          items: [
            "account-management/accounts",
            "account-management/organizations",
            "account-management/billing",
          ],
        },
        {
          type: "category",
          label: "Buckets",
          items: [
            "buckets/create-bucket",
            "buckets/bucket-rules",
            "buckets/locations",
            "buckets/public-bucket",
            "buckets/cors",
            "buckets/custom-domain",
            "buckets/objects-expiration",
            "buckets/object-lifecycle-rules",
            "buckets/object-notifications",
            "buckets/settings/index",
            "buckets/sharing",
          ],
        },
        {
          type: "category",
          label: "Objects",
          items: [
            "objects/tiers",
            "objects/caching",
            "objects/conditionals",
            "objects/query-metadata",
            "objects/presigned",
            "objects/upload-via-html-form",
            "objects/access-objects-via-cookies",
            "objects/acl",
            "objects/object-rename",
            "objects/bundle",
          ],
        },
        {
          type: "category",
          label: "IAM",
          items: [
            "iam/index",
            "iam/manage-access-key/index",
            "iam/policies/index",
            "iam/policies/supported-actions",
            "iam/policies/attach-iam-policy",
            "iam/policies/detach-iam-policy",
            {
              type: "category",
              label: "Example Policies",
              collapsible: true,
              collapsed: false,
              items: [
                "iam/policies/examples/ip-restrictions",
                "iam/policies/examples/date-time-restrictions",
                "iam/policies/examples/training-job",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Snapshots and Forks",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "About Snapshots and Forks",
              id: "snapshots-and-forks/index",
            },
            {
              type: "doc",
              label: "Snapshots",
              id: "snapshots/index",
            },
            {
              type: "doc",
              label: "Forks",
              id: "forks/index",
            },
            {
              type: "doc",
              label: "How to Use Snapshots and Forks",
              id: "buckets/snapshots-and-forks",
            },
            {
              type: "doc",
              label: "Use with the Tigris SDK",
              id: "sdks/tigris/snapshots-and-forks",
            },
          ],
        },
        {
          type: "category",
          label: "Tigris Acceleration Gateway",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "Overview",
              id: "acceleration-gateway/index",
            },
            {
              type: "doc",
              label: "Quick Start",
              id: "acceleration-gateway/quickstart",
            },
            {
              type: "doc",
              label: "Architecture",
              id: "acceleration-gateway/architecture",
            },
            {
              type: "doc",
              label: "Benchmarks",
              id: "acceleration-gateway/benchmarks",
            },
            {
              type: "category",
              label: "Deployment",
              collapsible: true,
              link: {
                type: "doc",
                id: "acceleration-gateway/deployment-guide",
              },
              items: [
                {
                  type: "doc",
                  label: "Native Binary",
                  id: "acceleration-gateway/native",
                },
                {
                  type: "doc",
                  label: "Docker",
                  id: "acceleration-gateway/docker",
                },
                {
                  type: "doc",
                  label: "Kubernetes",
                  id: "acceleration-gateway/kubernetes",
                },
              ],
            },
            {
              type: "category",
              label: "Reference",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  label: "Configuration",
                  id: "acceleration-gateway/configuration",
                },
                {
                  type: "doc",
                  label: "S3 Client Usage",
                  id: "acceleration-gateway/usage",
                },
                {
                  type: "doc",
                  label: "S3 Compatibility",
                  id: "acceleration-gateway/s3-compatibility",
                },
                {
                  type: "doc",
                  label: "Cache Control",
                  id: "acceleration-gateway/cache-control",
                },
                {
                  type: "doc",
                  label: "TLS",
                  id: "acceleration-gateway/tls",
                },
                {
                  type: "doc",
                  label: "Security",
                  id: "acceleration-gateway/security",
                },
                {
                  type: "doc",
                  label: "Metrics",
                  id: "acceleration-gateway/metrics",
                },
              ],
            },
          ],
        },
        "training/tigrisfs",
        {
          type: "doc",
          label: "Changelog",
          id: "changelog/index",
        },
      ],
    },
    {
      type: "category",
      label: "Partner Integration Program",
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "Overview",
          id: "partner-integrations/index",
        },
        {
          type: "doc",
          label: "Partner Dashboard",
          id: "partner-integrations/dashboard",
        },
        {
          type: "doc",
          label: "Multi-Tenant Architecture",
          id: "partner-integrations/architecture",
        },
        {
          type: "link",
          label: "API Reference",
          href: "/docs/partner-integrations/api/",
        },
      ],
    },
    {
      type: "category",
      label: "SDKs",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Tigris SDK",
          items: [
            {
              type: "doc",
              label: "Getting Started",
              id: "sdks/tigris/index",
            },
            "sdks/tigris/using-sdk",
            "sdks/tigris/client-uploads",
            {
              type: "doc",
              label: "Snapshots and Forks",
              id: "sdks/tigris/snapshots-and-forks",
            },
            "sdks/tigris/examples",
            "sdks/tigris/api",
          ],
        },
        {
          type: "category",
          label: "AWS S3 SDKs",
          link: {
            type: "doc",
            id: "sdks/s3/index",
          },
          items: [
            "sdks/s3/aws-cli",
            "sdks/s3/aws-js-sdk",
            "sdks/s3/aws-go-sdk",
            "sdks/s3/aws-java-sdk",
            "sdks/s3/aws-python-sdk",
            "sdks/s3/aws-php-sdk",
            "sdks/s3/aws-elixir-sdk",
            "sdks/s3/aws-ruby-sdk",
            "sdks/s3/aws-net-sdk",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "CLI",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "cli/index",
      },
      items: [
        "cli/configure",
        {
          type: "category",
          label: "tigris login",
          link: { type: "doc", id: "cli/login" },
          items: ["cli/login/oauth", "cli/login/credentials"],
        },
        "cli/whoami",
        "cli/logout",
        {
          type: "category",
          label: "tigris credentials",
          link: { type: "doc", id: "cli/credentials" },
          items: ["cli/credentials/test"],
        },
        "cli/ls",
        "cli/mk",
        "cli/touch",
        "cli/stat",
        "cli/presign",
        "cli/cp",
        "cli/mv",
        "cli/rm",
        {
          type: "category",
          label: "tigris organizations",
          link: { type: "doc", id: "cli/organizations" },
          items: [
            "cli/organizations/list",
            "cli/organizations/create",
            "cli/organizations/select",
          ],
        },
        {
          type: "category",
          label: "tigris buckets",
          link: { type: "doc", id: "cli/buckets" },
          items: [
            "cli/buckets/list",
            "cli/buckets/create",
            "cli/buckets/get",
            "cli/buckets/delete",
            "cli/buckets/set",
            "cli/buckets/set-ttl",
            "cli/buckets/set-migration",
            "cli/buckets/set-transition",
            "cli/buckets/set-notifications",
            "cli/buckets/set-cors",
          ],
        },
        {
          type: "category",
          label: "tigris forks",
          link: { type: "doc", id: "cli/forks" },
          items: ["cli/forks/list", "cli/forks/create"],
        },
        {
          type: "category",
          label: "tigris snapshots",
          link: { type: "doc", id: "cli/snapshots" },
          items: ["cli/snapshots/list", "cli/snapshots/take"],
        },
        {
          type: "category",
          label: "tigris objects",
          link: { type: "doc", id: "cli/objects" },
          items: [
            "cli/objects/list",
            "cli/objects/get",
            "cli/objects/put",
            "cli/objects/delete",
            "cli/objects/set",
          ],
        },
        {
          type: "category",
          label: "tigris access-keys",
          link: { type: "doc", id: "cli/access-keys" },
          items: [
            "cli/access-keys/list",
            "cli/access-keys/create",
            "cli/access-keys/delete",
            "cli/access-keys/get",
            "cli/access-keys/assign",
          ],
        },
        {
          type: "category",
          label: "tigris iam",
          link: { type: "doc", id: "cli/iam" },
          items: [
            {
              type: "category",
              label: "tigris iam policies",
              link: { type: "doc", id: "cli/iam/policies" },
              items: [
                "cli/iam/policies/list",
                "cli/iam/policies/get",
                "cli/iam/policies/create",
                "cli/iam/policies/edit",
                "cli/iam/policies/delete",
              ],
            },
            {
              type: "category",
              label: "tigris iam users",
              link: { type: "doc", id: "cli/iam/users" },
              items: [
                "cli/iam/users/list",
                "cli/iam/users/invite",
                "cli/iam/users/revoke-invitation",
                "cli/iam/users/update-role",
                "cli/iam/users/remove",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "AI",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "MCP",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "Local MCP Server",
              id: "mcp/local",
            },
            {
              type: "doc",
              label: "Remote MCP Server",
              id: "mcp/remote",
            },
          ],
        },
        {
          type: "doc",
          label: "Agent Skills",
          id: "skills",
        },
        {
          type: "doc",
          label: "Agent Plugins",
          id: "ai/agent-plugins",
        },
      ],
    },
    {
      type: "category",
      label: "Pricing",
      collapsed: true,
      items: ["pricing/index", "pricing/compare", "pricing/faqs"],
    },
    {
      type: "doc",
      label: "Support",
      id: "support/index",
    },
    {
      type: "category",
      label: "Legal",
      collapsed: true,
      items: [
        "legal/privacy-policy",
        "legal/service-terms",
        "legal/data-processing",
        "legal/sla",
      ],
    },
  ],
};

module.exports = sidebars;
