/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
// };

import apisidebar from "./docs/partner-integrations/api/sidebar.ts";
/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  quickstarts: [
    {
      type: "doc",
      label: "Home",
      id: "index",
    },
    {
      type: "category",
      label: "Overview",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "What is Tigris?",
          id: "overview/index",
        },
        "concepts/architecture",
        "concepts/authnz",
        "api/s3/index",
        "concepts/regions",
        "concepts/consistency",
      ],
    },
    {
      type: "doc",
      label: "Get Started",
      id: "get-started/index",
    },
    {
      type: "category",
      label: "Benchmarks",
      link: {
        type: "doc",
        id: "overview/benchmarks/index",
      },
      items: [
        {
          type: "doc",
          label: "Performance Metrics",
          id: "overview/benchmarks/metrics",
        },
        {
          type: "doc",
          label: "Comparison: AWS S3",
          id: "overview/benchmarks/aws-s3",
        },
        {
          type: "doc",
          label: "Comparison: Cloudflare R2",
          id: "overview/benchmarks/cloudflare-r2",
        },
        {
          type: "doc",
          label: "Benchmark Summary",
          id: "overview/benchmarks/summary",
        },
      ],
    },
    {
      type: "category",
      label: "Product",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Account Management",
          items: [
            "account-management/accounts",
            "account-management/organizations",
            "account-management/billing",
          ],
        },
        {
          type: "category",
          label: "Buckets",
          items: [
            "buckets/create-bucket",
            "buckets/bucket-rules",
            "buckets/public-bucket",
            "buckets/multi-region",
            "buckets/cors",
            "buckets/custom-domain",
            "buckets/objects-expiration",
            "buckets/object-lifecycle-rules",
            "buckets/object-notifications",
            "buckets/settings/index",
            "buckets/sharing",
          ],
        },
        {
          type: "category",
          label: "Objects",
          items: [
            "objects/tiers",
            "objects/caching",
            "objects/object_regions",
            "objects/consistency",
            "objects/conditionals",
            "objects/query-metadata",
            "objects/presigned",
            "objects/upload-via-html-form",
            "objects/access-objects-via-cookies",
            "objects/acl",
            "objects/object-rename",
          ],
        },
        {
          type: "category",
          label: "IAM",
          items: [
            "iam/index",
            "iam/manage-access-key/index",
            "iam/policies/index",
            "iam/policies/supported-actions",
            "iam/policies/attach-iam-policy",
            "iam/policies/detach-iam-policy",
            {
              type: "category",
              label: "Example Policies",
              collapsible: true,
              collapsed: false,
              items: [
                "iam/policies/examples/ip-restrictions",
                "iam/policies/examples/date-time-restrictions",
                "iam/policies/examples/training-job",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Snapshots and Forks",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "About Snapshots and Forks",
              id: "snapshots-and-forks/index",
            },
            {
              type: "doc",
              label: "Snapshots",
              id: "snapshots/index",
            },
            {
              type: "doc",
              label: "Forks",
              id: "forks/index",
            },
            {
              type: "doc",
              label: "How to Use Snapshots and Forks",
              id: "buckets/snapshots-and-forks",
            },
            {
              type: "doc",
              label: "Use with the Tigris SDK",
              id: "sdks/tigris/snapshots-and-forks",
            },
          ],
        },
        "training/tigrisfs",
        {
          type: "doc",
          label: "Changelog",
          id: "changelog/index",
        },
      ],
    },
    {
      type: "category",
      label: "MCP",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Local MCP Server",
          id: "mcp/local",
        },
        {
          type: "doc",
          label: "Remote MCP Server",
          id: "mcp/remote",
        },
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "LanceDB",
          items: [
            {
              type: "doc",
              label: "Getting Started",
              id: "libraries/lancedb/index",
            },
            {
              type: "doc",
              label: "Choosing a Lance Dataset Type",
              id: "libraries/lancedb/choosing-dataset-type",
            },
            {
              type: "doc",
              label: "Vector Database Tutorial",
              id: "libraries/lancedb/vector-database",
            },
            {
              type: "doc",
              label: "Example: Document Search",
              id: "libraries/lancedb/docs-search",
            },
            {
              type: "doc",
              label: "Mixpeek",
              id: "guides/mixpeek",
            },
          ],
        },
        {
          type: "doc",
          label: "DuckDB",
          id: "quickstarts/duckdb",
        },
        {
          type: "doc",
          label: "Bufstream",
          id: "quickstarts/bufstream",
        },
        {
          type: "doc",
          label: "AutoMQ",
          id: "quickstarts/automq",
        },
        {
          type: "category",
          label: "Fly.io",
          items: [
            {
              type: "doc",
              label: "Getting Started",
              id: "sdks/fly/index",
            },
            {
              type: "doc",
              label: "Data Migration with Flyctl",
              id: "sdks/fly/data-migration-with-flyctl",
            },
            {
              type: "doc",
              label: "Model Storage",
              id: "model-storage/fly-io",
            },
          ],
        },
        {
          type: "doc",
          label: "Pixeltable",
          id: "quickstarts/pixeltable",
        },
        {
          type: "doc",
          label: "PyTorch",
          id: "quickstarts/pytorch",
        },
        {
          type: "category",
          label: "SkyPilot",
          items: [
            {
              type: "doc",
              label: "Getting Started",
              id: "quickstarts/skypilot",
            },
            {
              type: "doc",
              label: "Model Storage",
              id: "model-storage/skypilot",
            },
            {
              type: "doc",
              label: "Training With Big Data",
              id: "training/big-data-skypilot/index",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsible: true,
      collapsed: false,
      items: [
        "quickstarts/go",
        "quickstarts/kubernetes",
        "quickstarts/mcp",
        "quickstarts/node",
        "quickstarts/rclone",
      ],
    },
    {
      type: "category",
      label: "Tigris SDK",
      items: [
        {
          type: "doc",
          label: "Getting Started",
          id: "sdks/tigris/index",
        },
        "sdks/tigris/using-sdk",
        "sdks/tigris/client-uploads",
        {
          type: "doc",
          label: "Snapshots and Forks",
          id: "sdks/tigris/snapshots-and-forks",
        },
        "sdks/tigris/examples",
      ],
    },
    {
      type: "category",
      label: "AWS S3 SDKs",
      link: {
        type: "doc",
        id: "sdks/s3/index",
      },
      items: [
        "sdks/s3/aws-cli",
        "sdks/s3/aws-js-sdk",
        "sdks/s3/aws-go-sdk",
        "sdks/s3/aws-java-sdk",
        "sdks/s3/aws-python-sdk",
        "sdks/s3/aws-php-sdk",
        "sdks/s3/aws-elixir-sdk",
        "sdks/s3/aws-ruby-sdk",
        "sdks/s3/aws-net-sdk",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "migration/index",
        {
          type: "category",
          label: "Model Storage",
          link: {
            type: "doc",
            id: "model-storage/index",
          },
          items: [
            {
              type: "doc",
              label: "Beam Cloud",
              id: "model-storage/beam-cloud",
            },
            {
              type: "doc",
              label: "Vast.ai",
              id: "model-storage/vast-ai",
            },
          ],
        },
        "training/csi-s3/index",
        "apps/docker-registry",
        "libraries/databricks/index",
        "terraform/index",
        {
          type: "doc",
          label: "Warpstream",
          id: "guides/warpstream",
        },
      ],
    },
    {
      type: "category",
      label: "Partner Integration Program",
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "Overview",
          id: "partner-integrations/index",
        },
        {
          type: "doc",
          label: "Multi-Tenant Architecture",
          id: "partner-integrations/architecture",
        },
        {
          type: "category",
          label: "API reference",
          link: {
            type: "generated-index",
            title: "Partner Integrations API reference",
            slug: "/partner-integrations/api/",
            description: "OpenAPI spec for Tigris parter extensions API.",
          },
          items: apisidebar,
        },
      ],
    },
    {
      type: "doc",
      label: "Pricing",
      id: "pricing/index",
    },
    {
      type: "doc",
      label: "Support",
      id: "support/index",
    },
    {
      type: "category",
      label: "Legal",
      items: [
        "legal/privacy-policy",
        "legal/service-terms",
        "legal/data-processing",
        "legal/sla",
      ],
    },
  ],
};

module.exports = sidebars;
